#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.
# x86-64: system call number in rax, arguments in rdi, rsi, rdx,
# r10, r8, r9 (as on Linux), and int $64 (T_SYSCALL) to enter the kernel.

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $prefix = "sys_";
    my $name = shift;
    if ($name eq "sbrk") {
	print ".global $prefix$name\n";
	print "$prefix$name:\n";
    } else {
	print ".global $name\n";
	print "$name:\n";
    }
    print " movq \$SYS_${name}, %rax\n";
    print " movq %rcx, %r10\n";
    print " int \$64\n";
    print " ret\n";
}
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("pause");
entry("uptime");
entry("sync");
